[package]
name = "crypto-seal"
version = "0.1.0"
edition = "2024"
authors = ["GlorYouth <admin@gloryouth.com>"]
description = "一个提供统一的框架来处理传统加密（RSA）、后量子加密（Kyber）以及两者的混合模式的库"
license = "MPL-2.0"
readme = "README.md"
keywords = ["cryptography", "post-quantum", "rsa", "kyber"]
categories = ["cryptography"]

[features]
default = ["traditional", "post-quantum", "secure-storage", "async-engine", "parallel", "chacha"]
traditional = ["rsa"]
post-quantum = ["pqcrypto-kyber", "pqcrypto-traits"]
secure-storage = ["argon2", "secrecy"]
async-engine = ["tokio", "async-trait"]
chacha = ["chacha20poly1305"]
parallel = ["rayon"]

[dependencies]
# 基础依赖
base64 = "0.22.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11"
secrecy = { version = "0.10.3", optional = true }
chrono = "0.4"
zeroize = { version = "1.8.1", features = ["derive"] }

# 传统加密相关
rsa = { version = "0.9.8", optional = true }
rand_core = "0.9.3"
sha2 = "0.10.9"

# 后量子加密相关
pqcrypto-kyber = { version = "0.8.1", optional = true }
pqcrypto-traits = { version = "0.3.5", optional = true }

# 安全存储相关
aes-gcm = "0.10.3"
chacha20poly1305 = { version = "0.10", optional = true }
argon2 = { version = "0.5.3", optional = true }
tempfile = "3.20.0"
uuid = { version = "1.17.0", features = ["v4"] }

# 可选依赖
dashmap = "6.1.0"
arc-swap = "1"
rayon = { version = "1.10.0", optional = true }
async-trait = { version = "0.1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }

[dev-dependencies]
criterion = "0.6"

[[bench]]
name = "base"
path = "benches/base.rs"
harness = false

[[bench]]
name = "parallel"
path = "benches/parallel.rs"
required-features = ["parallel"]
harness = false

[[bench]]
name = "async_engine"
path = "benches/async_engine.rs"
required-features = ["async-engine"]
harness = false

[[bench]]
name = "async_batch"
path = "benches/async_batch.rs"
required-features = ["async-engine", "parallel"]
harness = false
