[package]
name = "crypto-seal"
version = "0.1.0"
edition = "2024"
authors = ["GlorYouth <admin@gloryouth.com>"]
description = "一个提供统一的框架来处理传统加密（RSA）、后量子加密（Kyber）以及两者的混合模式的库"
license = "MPL-2.0"
readme = "README.md"
keywords = ["cryptography", "post-quantum", "rsa", "kyber"]
categories = ["cryptography"]

[features]
default = ["traditional", "post-quantum"]
traditional = ["rsa"]
post-quantum = ["pqcrypto-kyber", "pqcrypto-traits"]
secure-storage = []
async-engine = ["dashmap", "arc-swap"]

[dependencies]
# 基础依赖
rand = "0.9.1"
base64 = "0.22.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
secrecy = "0.10.3"
chrono = "0.4"
zeroize = { version = "1.8.1", features = ["derive"] }

# 传统加密相关
rsa = { version = "0.9.8", optional = true }
rand_core = "0.9.3"
sha2 = "0.10.9"

# 后量子加密相关
pqcrypto-kyber = { version = "0.8.1", optional = true }
pqcrypto-traits = { version = "0.3.5", optional = true }

# 安全存储相关
aes-gcm = "0.10.3"
argon2 = "0.5.3"
tempfile = "3.20.0"
uuid = { version = "1.17.0", features = ["v4"] }

# 可选依赖
dashmap = { version = "5", optional = true }
arc-swap = { version = "1", optional = true }

[dev-dependencies]
